"""add_minio_fields_to_ticket_attachments

Revision ID: 36a2d111a916
Revises: 68d74054af42
Create Date: 2025-09-21 09:18:09.839135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a2d111a916'
down_revision: Union[str, Sequence[str], None] = '68d74054af42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_attachments', sa.Column('bucket_name', sa.String(length=100), nullable=True), schema='ticket')
    op.add_column('ticket_attachments', sa.Column('is_image', sa.Boolean(), nullable=False, server_default=sa.text('false')), schema='ticket')
    op.add_column('ticket_attachments', sa.Column('image_width', sa.BigInteger(), nullable=True), schema='ticket')
    op.add_column('ticket_attachments', sa.Column('image_height', sa.BigInteger(), nullable=True), schema='ticket')
    op.add_column('ticket_attachments', sa.Column('usage_type', sa.String(length=50), nullable=False, server_default=sa.text("'attachment'")), schema='ticket')
    op.add_column('ticket_attachments', sa.Column('description', sa.Text(), nullable=True), schema='ticket')
    op.add_column('ticket_attachments', sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'completed'")), schema='ticket')
    op.add_column('ticket_attachments', sa.Column('file_url', sa.Text(), nullable=True), schema='ticket')
    op.add_column('ticket_attachments', sa.Column('url_expires_at', sa.DateTime(timezone=True), nullable=True), schema='ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_attachments', 'url_expires_at', schema='ticket')
    op.drop_column('ticket_attachments', 'file_url', schema='ticket')
    op.drop_column('ticket_attachments', 'status', schema='ticket')
    op.drop_column('ticket_attachments', 'description', schema='ticket')
    op.drop_column('ticket_attachments', 'usage_type', schema='ticket')
    op.drop_column('ticket_attachments', 'image_height', schema='ticket')
    op.drop_column('ticket_attachments', 'image_width', schema='ticket')
    op.drop_column('ticket_attachments', 'is_image', schema='ticket')
    op.drop_column('ticket_attachments', 'bucket_name', schema='ticket')
    # ### end Alembic commands ###
