"""001_init

Revision ID: 68d74054af42
Revises: 
Create Date: 2025-09-20 09:16:45.899065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d74054af42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ticket'
    )
    op.create_table('labels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ticket'
    )
    op.create_table('approval_template_steps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('approval_template_id', sa.BigInteger(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_template_id'], ['ticket.approval_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    op.create_table('ticket_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_fields_schema', sa.JSON(), nullable=True),
    sa.Column('approval_template_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_template_id'], ['ticket.approval_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    op.create_table('ticket_template_categories',
    sa.Column('ticket_template_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ticket.categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_template_id'], ['ticket.ticket_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_template_id', 'category_id'),
    schema='ticket'
    )
    op.create_table('ticket_template_labels',
    sa.Column('ticket_template_id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['ticket.labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_template_id'], ['ticket.ticket_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_template_id', 'label_id'),
    schema='ticket'
    )
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_no', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ticket_template_id', sa.BigInteger(), nullable=True),
    sa.Column('approval_template_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_fields_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'WAITING_APPROVAL', 'REJECTED', 'OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'CANCELLED', name='ticket_status', schema='ticket'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticket_priority', schema='ticket'), nullable=True),
    sa.Column('visibility', sa.Enum('INTERNAL', 'RESTRICTED', name='ticket_visibility', schema='ticket'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['approval_template_id'], ['ticket.approval_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_template_id'], ['ticket.ticket_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no'),
    schema='ticket'
    )
    op.create_table('approval_processes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('approval_template_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_process_status', schema='ticket'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_template_id'], ['ticket.approval_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id'),
    schema='ticket'
    )
    op.create_table('notification_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_template_id', sa.BigInteger(), nullable=True),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('notify_on_event', sa.Enum('ON_CREATE', 'ON_CLOSE', 'ON_STATUS_CHANGE', 'ON_NEW_COMMENT', name='notification_event', schema='ticket'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_template_id'], ['ticket.ticket_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    op.create_table('ticket_attachments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    op.create_table('ticket_categories',
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ticket.categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'category_id'),
    schema='ticket'
    )
    op.create_table('ticket_labels',
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['ticket.labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'label_id'),
    schema='ticket'
    )
    op.create_table('ticket_notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.Column('event_type', sa.Enum('STATE_CHANGE', 'TITLE_CHANGE', 'DESCRIPTION_CHANGE', 'STATUS_CHANGE', 'PRIORITY_CHANGE', 'ASSIGNEE_CHANGE', 'DUE_DATE_CHANGE', 'ATTACHMENT_ADD', 'ATTACHMENT_REMOVE', 'APPROVAL_SUBMITTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', 'LABEL_ADD', 'LABEL_REMOVE', name='ticket_event_type', schema='ticket'), nullable=True),
    sa.Column('event_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    op.create_table('ticket_view_permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'user_id', 'role_id'),
    schema='ticket'
    )
    op.create_table('approval_process_steps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('approval_process_id', sa.BigInteger(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('proxy_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_process_step_status', schema='ticket'), nullable=False),
    sa.Column('action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_process_id'], ['ticket.approval_processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    op.create_table('notification_rule_roles',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['ticket.notification_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'role_id'),
    schema='ticket'
    )
    op.create_table('notification_rule_users',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['ticket.notification_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'user_id'),
    schema='ticket'
    )
    op.create_table('ticket_note_attachments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['ticket.ticket_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_note_attachments', schema='ticket')
    op.drop_table('notification_rule_users', schema='ticket')
    op.drop_table('notification_rule_roles', schema='ticket')
    op.drop_table('approval_process_steps', schema='ticket')
    op.drop_table('ticket_view_permissions', schema='ticket')
    op.drop_table('ticket_notes', schema='ticket')
    op.drop_table('ticket_labels', schema='ticket')
    op.drop_table('ticket_categories', schema='ticket')
    op.drop_table('ticket_attachments', schema='ticket')
    op.drop_table('notification_rules', schema='ticket')
    op.drop_table('approval_processes', schema='ticket')
    op.drop_table('tickets', schema='ticket')
    op.drop_table('ticket_template_labels', schema='ticket')
    op.drop_table('ticket_template_categories', schema='ticket')
    op.drop_table('ticket_templates', schema='ticket')
    op.drop_table('approval_template_steps', schema='ticket')
    op.drop_table('labels', schema='ticket')
    op.drop_table('categories', schema='ticket')
    op.drop_table('approval_templates', schema='ticket')
    # ### end Alembic commands ###
