"""002_update_models

Revision ID: 865d38f4b310
Revises: 68d74054af42
Create Date: 2025-10-10 11:48:50.620466

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "865d38f4b310"
down_revision: str | Sequence[str] | None = "68d74054af42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types if they don't exist
    op.execute(
        "DO $$ BEGIN CREATE TYPE ticket.attachment_usage_type AS ENUM ('INLINE', 'GENERAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE ticket.approval_step_type AS ENUM ('ALL', 'ANY'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE ticket.approval_process_step_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )

    op.create_table(
        "attachments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("related_type", sa.String(length=50), nullable=False),
        sa.Column("related_id", sa.BigInteger(), nullable=False),
        sa.Column("ticket_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "usage_type",
            postgresql.ENUM("INLINE", "GENERAL", name="attachment_usage_type", schema="ticket", create_type=False),
            nullable=False,
        ),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("storage_provider", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="ticket",
    )
    op.create_table(
        "approval_template_step_approvers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("approval_template_step_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["approval_template_step_id"], ["ticket.approval_template_steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("approval_template_step_id", "role_id", "user_id"),
        schema="ticket",
    )
    op.create_table(
        "approval_process_step_approvers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("approval_process_step_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("actioned_by_id", sa.BigInteger(), nullable=True),
        sa.Column("delegated_for_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "APPROVED", "REJECTED", name="approval_process_step_status", schema="ticket", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("action_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["approval_process_step_id"], ["ticket.approval_process_steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="ticket",
    )
    op.drop_table("ticket_note_attachments", schema="ticket")
    op.drop_table("ticket_attachments", schema="ticket")
    op.add_column(
        "approval_process_steps",
        sa.Column(
            "approval_type",
            postgresql.ENUM("ALL", "ANY", name="approval_step_type", schema="ticket", create_type=False),
            nullable=False,
        ),
        schema="ticket",
    )
    op.add_column("approval_process_steps", sa.Column("is_deleted", sa.Boolean(), nullable=False), schema="ticket")
    op.drop_column("approval_process_steps", "proxy_id", schema="ticket")
    op.drop_column("approval_process_steps", "comment", schema="ticket")
    op.drop_column("approval_process_steps", "action_at", schema="ticket")
    op.drop_column("approval_process_steps", "approver_id", schema="ticket")
    op.drop_column("approval_process_steps", "deleted_at", schema="ticket")
    op.drop_column("approval_process_steps", "deleted_by", schema="ticket")
    op.add_column("approval_processes", sa.Column("is_deleted", sa.Boolean(), nullable=False), schema="ticket")
    op.drop_column("approval_processes", "deleted_at", schema="ticket")
    op.drop_column("approval_processes", "deleted_by", schema="ticket")
    op.add_column(
        "approval_template_steps",
        sa.Column(
            "approval_type",
            postgresql.ENUM("ALL", "ANY", name="approval_step_type", schema="ticket", create_type=False),
            nullable=False,
        ),
        schema="ticket",
    )
    op.add_column("approval_template_steps", sa.Column("is_deleted", sa.Boolean(), nullable=False), schema="ticket")
    op.drop_column("approval_template_steps", "is_mandatory", schema="ticket")
    op.drop_column("approval_template_steps", "role_id", schema="ticket")
    op.drop_column("approval_template_steps", "deleted_at", schema="ticket")
    op.drop_column("approval_template_steps", "user_id", schema="ticket")
    op.drop_column("approval_template_steps", "deleted_by", schema="ticket")
    op.add_column("approval_templates", sa.Column("is_deleted", sa.Boolean(), nullable=False), schema="ticket")
    op.drop_column("approval_templates", "deleted_at", schema="ticket")
    op.drop_column("approval_templates", "deleted_by", schema="ticket")
    op.add_column("categories", sa.Column("is_deleted", sa.Boolean(), nullable=False), schema="ticket")
    op.drop_column("categories", "deleted_at", schema="ticket")
    op.drop_column("categories", "deleted_by", schema="ticket")
    op.add_column("labels", sa.Column("is_deleted", sa.Boolean(), nullable=False), schema="ticket")
    op.drop_column("labels", "deleted_at", schema="ticket")
    op.drop_column("labels", "deleted_by", schema="ticket")
    op.add_column("ticket_notes", sa.Column("is_deleted", sa.Boolean(), nullable=False), schema="ticket")
    op.drop_column("ticket_notes", "deleted_at", schema="ticket")
    op.drop_column("ticket_notes", "deleted_by", schema="ticket")
    op.add_column("ticket_templates", sa.Column("is_deleted", sa.Boolean(), nullable=False), schema="ticket")
    op.drop_column("ticket_templates", "deleted_at", schema="ticket")
    op.drop_column("ticket_templates", "deleted_by", schema="ticket")
    op.add_column("ticket_view_permissions", sa.Column("created_by", sa.BigInteger(), nullable=False), schema="ticket")
    op.add_column(
        "ticket_view_permissions",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        schema="ticket",
    )
    op.add_column("ticket_view_permissions", sa.Column("updated_by", sa.BigInteger(), nullable=True), schema="ticket")
    op.add_column(
        "ticket_view_permissions", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True), schema="ticket"
    )
    op.add_column("tickets", sa.Column("is_deleted", sa.Boolean(), nullable=False), schema="ticket")
    op.drop_column("tickets", "deleted_at", schema="ticket")
    op.drop_column("tickets", "deleted_by", schema="ticket")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket")
    op.add_column(
        "tickets",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.drop_column("tickets", "is_deleted", schema="ticket")
    op.drop_column("ticket_view_permissions", "updated_at", schema="ticket")
    op.drop_column("ticket_view_permissions", "updated_by", schema="ticket")
    op.drop_column("ticket_view_permissions", "created_at", schema="ticket")
    op.drop_column("ticket_view_permissions", "created_by", schema="ticket")
    op.add_column("ticket_templates", sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket")
    op.add_column(
        "ticket_templates",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.drop_column("ticket_templates", "is_deleted", schema="ticket")
    op.add_column("ticket_notes", sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket")
    op.add_column(
        "ticket_notes",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.drop_column("ticket_notes", "is_deleted", schema="ticket")
    op.add_column("labels", sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket")
    op.add_column(
        "labels",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.drop_column("labels", "is_deleted", schema="ticket")
    op.add_column("categories", sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket")
    op.add_column(
        "categories",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.drop_column("categories", "is_deleted", schema="ticket")
    op.add_column(
        "approval_templates", sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.add_column(
        "approval_templates",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.drop_column("approval_templates", "is_deleted", schema="ticket")
    op.add_column(
        "approval_template_steps", sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.add_column(
        "approval_template_steps", sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.add_column(
        "approval_template_steps",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.add_column(
        "approval_template_steps", sa.Column("role_id", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.add_column(
        "approval_template_steps", sa.Column("is_mandatory", sa.BOOLEAN(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.drop_column("approval_template_steps", "is_deleted", schema="ticket")
    op.drop_column("approval_template_steps", "approval_type", schema="ticket")
    op.add_column(
        "approval_processes", sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.add_column(
        "approval_processes",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.drop_column("approval_processes", "is_deleted", schema="ticket")
    op.add_column(
        "approval_process_steps", sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.add_column(
        "approval_process_steps",
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.add_column(
        "approval_process_steps", sa.Column("approver_id", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.add_column(
        "approval_process_steps",
        sa.Column("action_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        schema="ticket",
    )
    op.add_column(
        "approval_process_steps", sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.add_column(
        "approval_process_steps", sa.Column("proxy_id", sa.BIGINT(), autoincrement=False, nullable=True), schema="ticket"
    )
    op.drop_column("approval_process_steps", "is_deleted", schema="ticket")
    op.drop_column("approval_process_steps", "approval_type", schema="ticket")
    op.create_table(
        "ticket_attachments",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("file_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("file_path", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("file_size", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("mime_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("updated_by", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["ticket.tickets.id"], name=op.f("ticket_attachments_ticket_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ticket_attachments_pkey")),
        schema="ticket",
    )
    op.create_table(
        "ticket_note_attachments",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("note_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("file_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("file_size", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("mime_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("created_by", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"], ["ticket.ticket_notes.id"], name=op.f("ticket_note_attachments_note_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ticket_note_attachments_pkey")),
        schema="ticket",
    )
    op.drop_table("approval_process_step_approvers", schema="ticket")
    op.drop_table("approval_template_step_approvers", schema="ticket")
    op.drop_table("attachments", schema="ticket")
    # ### end Alembic commands ###
