"""Init

Revision ID: 9ce75d6154a8
Revises: 
Create Date: 2025-09-15 22:02:27.232252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce75d6154a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='ticket'
    )
    op.create_index(op.f('ix_ticket_users_id'), 'users', ['id'], unique=False, schema='ticket')
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED', name='ticket_status', schema='ticket'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ticket.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    op.create_index(op.f('ix_ticket_tickets_id'), 'tickets', ['id'], unique=False, schema='ticket')
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ticket.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ticket'
    )
    op.create_index(op.f('ix_ticket_comments_id'), 'comments', ['id'], unique=False, schema='ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='comments', schema='ticket')
    op.drop_table('comments', schema='ticket')
    op.drop_index(op.f('ix_ticket_tickets_id'), table_name='tickets', schema='ticket')
    op.drop_table('tickets', schema='ticket')
    op.drop_index(op.f('ix_ticket_users_id'), table_name='users', schema='ticket')
    op.drop_table('users', schema='ticket')
    # ### end Alembic commands ###
