"""003_allow_null_values_for_attachments

Revision ID: e15c3864e8a4
Revises: 865d38f4b310
Create Date: 2025-10-11 22:53:42.578291

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e15c3864e8a4"
down_revision: str | Sequence[str] | None = "865d38f4b310"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("attachments", "related_type", existing_type=sa.VARCHAR(length=50), nullable=True, schema="ticket")
    op.alter_column("attachments", "related_id", existing_type=sa.BIGINT(), nullable=True, schema="ticket")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("attachments", "related_id", existing_type=sa.BIGINT(), nullable=False, schema="ticket")
    op.alter_column("attachments", "related_type", existing_type=sa.VARCHAR(length=50), nullable=False, schema="ticket")
    # ### end Alembic commands ###
